global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:4000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']